spring:
  data:
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379
  datasource:
    name: rocketmq
    url: jdbc:mysql://127.0.0.1:3307/jwt?autoReconnect=true&useSSL=false
    username: root
    password: Zz@095718
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml